apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: phone-alert-config
  namespace: monitoring
  labels:
    alertcfg: enabled
spec:
  route:
    receiver: 'aws-lambda-phone'
    groupWait: 30s      # 30초 동안 알람 모으기
    groupInterval: 5m   # 첫 알람 이후 추가 알람은 5분 단위로 묶어서 발송 (람다 절약)
    repeatInterval: 12h # 똑같은 알람은 12시간에 한 번만 (지갑 수호)
    matchers: []
  receivers:
    - name: 'aws-lambda-phone'
      webhookConfigs:
        - url: 'https://hkclepuol5tkqre3vffkztf3c40abpcc.lambda-url.us-west-2.on.aws/'
          sendResolved: true # 해결됐을 때만 한 번 더 옴
