apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: phone-alert-config
  namespace: monitoring # Alertmanager가 떠 있는 네임스페이스
  labels:
    alertcfg: enabled # Operator가 이 설정을 읽어갈 수 있게 라벨 부여
spec:
  route:
    receiver: 'aws-lambda-phone'
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h # 1시간에 한 번만 전화 오게
    matchers:
      - name: severity
        value: critical # severity가 critical인 알람만 필터링
  receivers:
    - name: 'aws-lambda-phone'
      webhookConfigs:
        - url: 'https://hkclepuol5tkqre3vffkztf3c40abpcc.lambda-url.us-west-2.on.aws/' # 네 람다 주소
