apiVersion: v1
kind: Service
metadata:
  name: ebpf-exporter
  namespace: monitoring
  labels:
    app: ebpf-exporter # ServiceMonitor가 이 라벨을 보고 찾습니다.
spec:
  ports:
  - name: metrics
    port: 9435
    targetPort: 9435
  selector:
    app: ebpf-exporter # 실제 DaemonSet Pod들을 가리킵니다.
