apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: high-cpu-alerts
  namespace: monitoring
  labels:
    release: kube-prom # Operator가 읽을 수 있도록 설치된 release 라벨과 맞춰주세요
spec:
  groups:
  - name: cpu-alerts
    rules:
    - alert: AllCpusHighLoad
      # 10%만 넘어도 알람 터지게 수정 (테스트용)
      expr: |
        min by (instance) (
          100 - (irate(node_cpu_seconds_total{mode="idle"}[5m]) * 100)
        ) > 90 
      for: 60s # 60초만 유지되면 바로 발사!
      labels:
        severity: critical
