apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: yjmatzip
resources:
  - postgres-secret.yaml
  - postgres-pvc.yaml
  - postgres-full.yaml
  - backend-deployment.yaml
  - matzip-ingress.yaml
