apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: yjmatzip
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # NucBox 용량을 고려해 5GB로 설정
